/*
 * LCD_Config.h
 *
 * Created: 3/19/2022 3:58:41 AM
 *  Author: Ahmed
 */ 


#ifndef LCD_CONFIG_H_
#define LCD_CONFIG_H_

/*Function Set*/

/*LCD MODE			EIGHT_BIT_MODE		or		FOUR_BIT_MODE*/
#define DL_LCD_MODE	FOUR_BIT_MODE
/*DISPLAY_LINES		SINGLE_LINE_MODE	or		DOUBLE_LINE_MODE*/
#define N_DISPLAY_LINES	DOUBLE_LINE_MODE
/*DISPLAY_FONT		FIVE_x7	or		FIVE_x11*/
#define F_DISPLAY_FONT	FIVE_x7

/*DISPLAY Control*/
/*DISPLAY_MODE		DISPLAY_ON		or		DISPLAY_OFF*/
#define D_DISPLAY_MODE	DISPLAY_ON
/*CURSOR_MODE		CURSOR_ON		or		CURSOR_OFF*/
#define C_CURSOR_MODE		CURSOR_OFF
/*BLINK_MODE		BLINK_ON		or		BLINK_OFF*/
#define B_BLINK_MODE		BLINK_OFF

/*Entry Mode Set*/
/*INCREMENT_MODE		INCREMENT		or		DECREMENT*/
#define ID_INCREMENT_MODE		INCREMENT
/*SHIFT_MODE		NO_DISPLAY_SHIFT		or		DISPLAY_SHIFT*/
#define SH_SHIFT_MODE		NO_DISPLAY_SHIFT


#define LCD_CTRL_RS_PORT		DIO_PORTB
#define LCD_CTRL_RS_PIN			DIO_Pin1
#define LCD_CTRL_RW_PORT		DIO_PORTB
#define LCD_CTRL_RW_PIN			DIO_Pin2		//Grounded
#define LCD_CTRL_EN_PORT		DIO_PORTB
#define LCD_CTRL_EN_PIN			DIO_Pin3

#define LCD_DATA_D4_PORT		DIO_PORTA
#define LCD_DATA_D4_PIN			DIO_Pin4
#define LCD_DATA_D5_PORT		DIO_PORTA
#define LCD_DATA_D5_PIN			DIO_Pin5
#define LCD_DATA_D6_PORT		DIO_PORTA
#define LCD_DATA_D6_PIN			DIO_Pin6
#define LCD_DATA_D7_PORT		DIO_PORTA
#define LCD_DATA_D7_PIN			DIO_Pin7


#define DATA_PATTERN0		0
#define DATA_PATTERN1		1
#define DATA_PATTERN2		2
#define DATA_PATTERN3		3
#define DATA_PATTERN4		4
#define DATA_PATTERN5		5
#define DATA_PATTERN6		6
#define DATA_PATTERN7		7


#endif /* LCD_CONFIG_H_ */
